version: "3.9"
services:
  prom:
    build: ./prometheus
    ports:
      - "${FP_PROM_PORT:-8061}:9090"
    volumes:
      - prometheus_data:/prometheus
  prometheus-push-gateway:
    build: ./prometheus-push-gateway
    ports:
      - "${FP_PUSH_GATEWAY_PORT:-8062}:80" # TODO
    env_file:
      # NOTE: "Last in wins" if there are duplicate env vars across multiple files
      - ./.env
  api:
    build: ./api
    ports:
      - "${FP_API_PORT:-8063}:8080"
    env_file:
      - ./.env
    environment:
      - AGGREGATION_GATEWAY_URL=http://prometheus-push-gateway:80/metrics
      - PROMETHEUS_URL=http://prom:9090
      - DEBUG=http-proxy-middleware*
volumes:
  prometheus_data:
