version: "3.9"
services:
  prom:
    build: ./prometheus
    ports:
      - "${FP_PROM_PORT:-8061}:9090"
    volumes:
      - prometheus_data:/prometheus
  prometheus-push-gateway:
    build: ./prometheus-push-gateway
    ports:
      - "${FP_PUSH_GATEWAY_PORT:-8062}:80" # TODO
    env_file:
      # NOTE: Later "last in wins" if there are duplicate env vars
      - ./.env
      - ./prometheus-push-gateway/.env
volumes:
  prometheus_data:
