version: "3.9"
services:
  prom:
    # Make host.docker.internal available for all? platforms
    # On certain platforms like linux or with certain alternatives for
    # docker host.docker.internal is not available. This is a workaround.
    # You can switch docker to host networking mode for unsupported platforms.
    extra_hosts:
      - host.docker.internal:host-gateway
    image: prom/prometheus
    ports:
      - "${FP_PROM_PORT:-9090}:9090"
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/autometrics.rules.yml:/etc/prometheus/autometrics.rules.yml
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  prometheus-push-gateway:
    image: ghcr.io/zapier/prom-aggregation-gateway:v0.7.0
    ports:
      - "${FP_PUSH_GATEWAY_PORT:-8081}:80" # TODO
    env_file:
      # NOTE: "Last in wins" if there are duplicate env vars across multiple files
      - ./.env

  grafana:
    image: grafana/grafana
    ports:
      - "${FP_GRAFANA_PORT:-9011}:9011"
    # FIXME - Because the dashboard json require an input to populate "uid": "${DS_PROMETHEUS}" field,
    #         we cannot autoload dashboard from this path, unfortunately!
    # environment:
    #   GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: "/var/lib/grafana/dashboards/Autometrics Overview.json"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      # FIXME - This encounters the same error described above re: autoloading dashboards
      #
      # - ./grafana/dashboards:/var/lib/grafana/dashboards

  api:
    build: ./api
    ports:
      - "${FP_API_PORT:-8082}:8080"
    env_file:
      - ./.env
    environment:
      - AGGREGATION_GATEWAY_URL=http://prometheus-push-gateway:80/metrics/
      - PROMETHEUS_URL=http://prom:9090
      - DEBUG=http-proxy-middleware*
volumes:
  prometheus_data:
  grafana_data:
