apiVersion: 1

datasources:
  - name: Prometheus (Quickmetrics)
    type: prometheus
    access: proxy
    orgId: 1
    # Use the name and container port from docker compose
    url: http://prom:9090
    basicAuth: false
    isDefault: false
    editable: true
  - name: Prometheus (AM)
    type: prometheus
    access: proxy
    orgId: 1
    # Use the name and container port from docker compose
    url: http://host.docker.internal:9090/prometheus
    basicAuth: false
    isDefault: true
    editable: true
